#display_max_edges.py
#displays maximum matching graph corresponding to edge-list generated by blossom.py


import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import sys


def draw_graph(graph, labels=None, graph_layout='shell',
               node_size=1600, node_color='blue', node_alpha=0.3,
               node_text_size=12,
               edge_color='blue', edge_alpha=0.3, edge_tickness=1,
               edge_text_pos=0.3,
               text_font='sans-serif'):

    # create networkx graph
    G=nx.Graph()

    # add edges
    for edge in graph:
        G.add_edge(edge[0], edge[1])

    # these are different layouts for the network you may try
    # shell seems to work best
    if graph_layout == 'spring':
        graph_pos=nx.spring_layout(G)
    elif graph_layout == 'spectral':
        graph_pos=nx.spectral_layout(G)
    elif graph_layout == 'random':
        graph_pos=nx.random_layout(G)
    else:
        graph_pos=nx.shell_layout(G)

    # draw graph
    nx.draw_networkx_nodes(G,graph_pos,node_size=node_size, 
                           alpha=node_alpha, node_color=node_color)
    nx.draw_networkx_edges(G,graph_pos,width=edge_tickness,
                           alpha=edge_alpha,edge_color=edge_color)
    nx.draw_networkx_labels(G, graph_pos,font_size=node_text_size,
                            font_family=text_font)

    if labels is None:
        labels = range(len(graph))

    edge_labels = dict(zip(graph, labels))
    nx.draw_networkx_edge_labels(G, graph_pos, edge_labels=edge_labels, 
                                 label_pos=edge_text_pos)

    # show graph
    plt.show()



fname = 'graph0_edges.txt'
if len(sys.argv) > 1:
    fname = sys.argv[1]

#create internal numpy adjacency matrix representation of matix csv-file
#display numeric representation and type
A = np.genfromtxt(fname, delimiter=',')
print(A)
print(type(A))

#convert array of pair-arrays to array of tuples
match_edges = tuple(map(tuple, A))
  
# print result
print ("match_edges:"+str(match_edges))
print ("type(match_edges):"+str(type(match_edges)))

#display
draw_graph(match_edges)



